name: Pull Request CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'lib/**'
      - 'test/**'
      - '.github/**'

jobs:
  # Prettierのチェック
  call-prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run Prettier Check
        uses: ./.github/actions/linter/prettier

  # ESLintのチェック
  call-eslint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ESLint Check
        uses: ./.github/actions/linter/eslint

  # TypeScriptの型チェック
  call-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run Type Check
        uses: ./.github/actions/linter/type-check

  # 単体テストの実行
  call-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run Unit Tests
        uses: ./.github/actions/test/unit

  # ITAテストの実行
  call-ita-test-jra:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For Jra
        uses: ./.github/actions/test/ita/jra

  call-ita-test-nar:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For Nar
        uses: ./.github/actions/test/ita/nar

  call-ita-test-world:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For World
        uses: ./.github/actions/test/ita/world

  call-ita-test-keirin:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For Keirin
        uses: ./.github/actions/test/ita/keirin

  call-ita-test-autorace:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For Autorace
        uses: ./.github/actions/test/ita/autorace

  call-ita-test-boatrace:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run ITA Tests For Boatrace
        uses: ./.github/actions/test/ita/boatrace